services:
  postgres: 
    image: postgres:17-alpine
    container_name: jommik-db
    ports:
    - 5432:5432
#    volumes:
#    - postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=parool
    networks:
    - pg_net
  pgadmin4:
    image: dpage/pgadmin4:8
    container_name: pgadmin4
    ports:
    - 8081:80
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=tarvo@domain.com
    - PGADMIN_DEFAULT_PASSWORD=salajane
    networks:
    - pg_net
networks:
  pg_net:
volumes:
  pgadmin-data:
# postgres-data: